#!/usr/bin/env node
const baseUrl = process.env.BASE_URL || 'http://localhost:3000';
const email = process.env.SMOKE_EMAIL || 'smoke@goal-idle.local';
const nickname = process.env.SMOKE_NICKNAME || 'smoke-user';
const password = process.env.SMOKE_PASSWORD || 'Smoke1234!';

async function request(method, path, body, token) {
  const headers = { 'Content-Type': 'application/json' };
  if (token) {
    headers.Authorization = `Bearer ${token}`;
  }

  const response = await fetch(`${baseUrl}${path}`, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
  });

  const raw = await response.text();
  let data;
  try {
    data = raw ? JSON.parse(raw) : {};
  } catch {
    data = raw;
  }

  if (!response.ok) {
    const message = typeof data === 'string'
      ? data
      : Array.isArray(data.message)
        ? data.message.join(', ')
        : data.message || JSON.stringify(data);
    throw new Error(`${method} ${path} -> ${response.status} ${message}`);
  }

  return data;
}

async function loginOrSignup() {
  try {
    const login = await request('POST', '/auth/login', { email, password });
    return login.accessToken;
  } catch {
    const signup = await request('POST', '/auth/signup', { email, nickname, password });
    return signup.accessToken;
  }
}

async function ensureGoalData(token) {
  const weekly = await request('GET', '/goals/weekly', undefined, token);
  if (Array.isArray(weekly) && weekly.length > 0) {
    return weekly[0];
  }

  const targetDate = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);
  const vision = await request('POST', '/goals/vision', {
    title: 'Smoke Test Vision',
    description: 'Generated by smoke test',
    targetDate,
  }, token);

  const generated = await request('POST', `/goals/vision/${vision.id}/weekly-plan`, {
    weeks: 1,
    targetCount: 3,
  }, token);

  const weeklyMission = generated[0];
  await request('POST', `/goals/weekly/${weeklyMission.id}/micro-generate`, { count: 3 }, token);
  return weeklyMission;
}

async function run() {
  const token = await loginOrSignup();
  const player = await request('GET', '/player/me', undefined, token);
  if (!player.userId) {
    throw new Error('player/me did not return userId');
  }

  const weeklyMission = await ensureGoalData(token);
  const microList = await request('GET', `/goals/weekly/${weeklyMission.id}/micro`, undefined, token);
  if (!Array.isArray(microList) || microList.length === 0) {
    throw new Error('No micro actions available after generation');
  }

  let nextMicro;
  try {
    nextMicro = await request('GET', '/actions/next-micro', undefined, token);
  } catch {
    nextMicro = microList.find((item) => item.status === 'OPEN');
  }

  if (!nextMicro) {
    throw new Error('No actionable micro found');
  }

  const completed = await request('POST', `/actions/micro/${nextMicro.id}/complete`, undefined, token);
  if (typeof completed.currentStreakDays !== 'number') {
    throw new Error('Micro completion did not update streak');
  }

  const consistency = await request('GET', '/consistency/me', undefined, token);
  const prediction = await request('POST', '/prediction/score', {
    durationMin: 20,
    difficulty: 2,
    historicalSuccessRate: 0.5,
    timeslotSuccessRate: 0.5,
    fatigueLevel: 1,
  }, token);
  const battle = await request('GET', '/idle/status', undefined, token);
  const idle = await request('POST', '/idle/claim', undefined, token);
  const shop = await request('GET', '/shop/costumes', undefined, token);

  console.log(JSON.stringify({
    ok: true,
    userId: player.userId,
    completedMicroId: nextMicro.id,
    streak: consistency.currentStreakDays,
    predictionScore: prediction.score,
    stageCount: Array.isArray(battle.stages) ? battle.stages.length : 0,
    idleGranted: idle.grantedIdleGold,
    costumeCount: Array.isArray(shop) ? shop.length : 0,
  }, null, 2));
}

run().catch((error) => {
  console.error('Smoke test failed:', error.message);
  process.exit(1);
});

